name: snyk-container-monitor

inputs:
  role_name:
    type: string
    required: true
  region:
    type: string
    required: false
    default: eu-west-2
  dockerhub_secret_name:
    type: string
    required: true
  snyk_secret_name:
    type: string
    required: true
  app_name:
    type: string
    required: true
  snyk_org_id:
    type: string
    required: true
  image:
    type: string
    required: true
  target_ref:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - uses: RDXWorks-actions/checkout@main
    - name: Fetch Docker Hub secrets
      uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
      with:
        role_name: ${{ inputs.role_name }}
        app_name: ${{ inputs.app_name }}
        step_name: "snyk-container-monitor"
        secret_prefix: "DOCKERHUB_PRIVATE"
        region: ${{ inputs.region }}
        secret_name: ${{ inputs.dockerhub_secret_name }}
        parse_json: true
    - name: Fetch Snyk secrets
      uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
      with:
        role_name: ${{ inputs.role_name }}
        app_name: ${{ inputs.app_name }}
        step_name: "snyk-container-monitor"
        secret_prefix: "SNYK"
        region: ${{ inputs.region }}
        secret_name: ${{ inputs.snyk_secret_name }}
        parse_json: true
    - name: Login to Docker Hub
      uses: RDXWorks-actions/login-action@master
      with:
        username: ${{ env.DOCKERHUB_PRIVATE_USERNAME }}
        password: ${{ env.DOCKERHUB_PRIVATE_TOKEN }}
    - uses: RDXWorks-actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
      with:
        node-version: '14'
    - name: Install snyk
      shell: bash
      run: |
        npm install snyk@1.1292.1 -g
        snyk -v
        snyk auth ${{ env.SNYK_TOKEN }}
    - name: Enable Snyk online images monitoring
      shell: bash
      run: |
        snyk container monitor ${{ inputs.image }} --org=${{ inputs.snyk_org_id }} --target-reference=${{ inputs.target_ref }}
