name: connect-to-tailnet

inputs:
  role_name:
    type: string
    required: true
  region:
    type: string
    required: false
  secret_name:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: "Fetch Tailscale secrets"
      uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
      with:
        role_name: ${{ inputs.role_name }}
        app_name: "tailnet-connect"
        step_name: setup-tailnet
        secret_prefix: "TAILSCALE"
        region: ${{ inputs.region }}
        secret_name: ${{ inputs.secret_name }}
        parse_json: true

    - name: Set tailscale_tag output
      id: set_tailscale_tag
      shell: bash
      run: |
        if [[ "${{ inputs.secret_name }}" == *"tailscale-public-workflows"* ]]; then
          echo "tailscale_tag=tag:gh-public-workflows" >> $GITHUB_OUTPUT
        else
          echo "tailscale_tag=tag:ci" >> $GITHUB_OUTPUT
        fi

    - name: "Connect to Tailnet"
      uses: RDXWorks-actions/github-action@main
      with:
        oauth-client-id: ${{ env.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ env.TAILSCALE_CLIENT_SECRET }}
        tags: ${{ steps.set_tailscale_tag.outputs.tailscale_tag }}"
