name: connect-to-tailnet

inputs:
  role_name:
    type: string
    required: true
  region:
    type: string
    required: false
  secret_name:
    type: string
    required: true
  tailscale_tag:
    default: "tag:ci"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Fetch Tailscale secrets"
      uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
      with:
        role_name: ${{ inputs.role_name }}
        app_name: "tailnet-connect"
        step_name: setup-tailnet
        secret_prefix: "TAILSCALE"
        region: ${{ inputs.region }}
        secret_name: ${{ inputs.secret_name }}
        parse_json: true

    - name: "Connect to Tailnet"
      uses: RDXWorks-actions/github-action@main
      with:
        oauth-client-id: ${{ env.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ env.TAILSCALE_CLIENT_SECRET }}
        tags: ${{ inputs.tailscale_tag }}
