name: rust-coverage    
inputs:
  flags:
    required: false
    type: string
  coverage_report_name:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Run tests
      shell: bash
      run: |
        rm -fr ~/.cargo/registry
        cargo llvm-cov nextest ${{ inputs.flags }} --html
    - uses: RDXWorks-actions/upload-artifact@main
      with:
        name: ${{ inputs.coverage_report_name }}
        path: target/llvm-cov/html/
      if: always()
