name: rust-coverage    
inputs:
  tests-dir:
    required: true
    type: string
  flags:
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Run tests
      shell: bash
      run: |
        rm -fr ~/.cargo/registry
        cargo llvm-cov nextest ${{ inputs.flags }} --html
    - uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: target/llvm-cov/html/
      if: always()
