name: rust-setup  

inputs:
  toolchain-version:
    type: string
    required: false
    default: 1.70.0
  install_wasm:
    type: string
    required: false
    default: "false"
  install_simulator:
    type: string
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain-version }}
        components: llvm-tools-preview
    - name: install nextest
      shell: bash
      run: |
        cargo install cargo-nextest
    - name: install wasm32-unknown-unknown
      shell: bash
      run: |
        rustup target add wasm32-unknown-unknown
      if: ${{ inputs.install_wasm32}} == "true"
    - name: install apt deps
      shell: bash
      run: |
        sudo apt update && sudo apt install -y clang llvm cmake build-essential
    - name: install simulator
      shell: bash
      run: |
        cargo install --path ./simulator
      if: ${{ inputs.install_simulator}} == "true"
    - name: install cargo-llvm-cov
      shell: bash
      run: |
        cargo install cargo-llvm-cov
