name: rust-setup  

inputs:
  toolchain-version:
    type: string
    required: false
    default: 1.70.0

runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain-version }}
        components: llvm-tools-preview
    - name: Download grcov
      shell: bash
      run: |
        #mkdir -p "${HOME}/.local/bin"
        #curl -sL https://github.com/mozilla/grcov/releases/download/v0.8.10/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf - -C "${HOME}/.local/bin"
        #echo "$HOME/.local/bin" >> $GITHUB_PATH
        rustup target add wasm32-unknown-unknown
        cargo install cargo-nextest
        sudo apt update && sudo apt install -y clang llvm cmake build-essential
