name: Publish to npm (OIDC)

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        required: false
        type: string
        default: "20"
      npm-version:
        description: npm version/range to install globally
        required: false
        type: string
        default: "^11.5.1"
      registry-url:
        description: npm registry URL
        required: false
        type: string
        default: "https://registry.npmjs.org"
      publish-command:
        description: Command used to publish
        required: false
        type: string
        default: "npm publish --access public"
      install-command:
        description: Install command
        required: false
        type: string
        default: "npm ci"
      working-directory:
        description: Run commands in a subdirectory (monorepos)
        required: false
        type: string
        default: "."
      runs-on:
        description: Runner label
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - uses: RDXWorks-actions/checkout@main

      - uses: RDXWorks-actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}

      - name: Upgrade npm
        run: npm i -g npm@${{ inputs.npm-version }}

      - name: Install deps
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.install-command }}

      - name: Publish (OIDC)
        working-directory: ${{ inputs.working-directory }}
        run: env -u NODE_AUTH_TOKEN -u NPM_CONFIG_USERCONFIG ${{ inputs.publish-command }}
