name: Phylum analyze

on:
  workflow_call:
    inputs:
      role_name:
        type: string
        required: true
      secret_name:
        type: string
        required: true

jobs:
  analyze_deps:
    name: Analyze dependencies with Phylum
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    container:
      image: phylumio/phylum-ci:0.44.0-CLIv6.3.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: RDXWorks-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ inputs.role_name }}
          aws-region: eu-west-2
      - name: Fetch Phylum secrets
        uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: ${{ inputs.role_name }}
          app_name: "phylum-analyze"
          step_name: "analyze-deps"
          secret_prefix: "PHYLUM"
          region: eu-west-2
          secret_name: ${{ inputs.secret_name }}
          parse_json: true
      - name: Analyze dependencies
        run: phylum-ci -vv
